### ISSUE TITLE
I have a Samsung S9

### ISSUE THREAD

**Issue by samuelfaj** [snt1017/cordova-plugin-power-optimization#1]
Dear friend, 
Firstly i would like to congrats you for the initiative.

I have a samsung s9 and will test your plugin.
Also have another phones using my app.

I'll reply this with my conclusions.

Together we're strong!

**Comment by snt1017** [comment]
Hello, thanks for collaborating!

Currently I test with a Huawei and found that in a last OS update, there was an error for a permission that was needed. I already updated the repository with the fix and added the compatibility with ES4.

Sorry to answer so far, but I was a bit busy.
