### ISSUE TITLE
How can i update default message?

### ISSUE THREAD

**Issue by Lucab95** [snt1017/cordova-plugin-power-optimization#3]
Is there a way to update the default alert called by RequestOptimizations()?

**Comment by snt1017** [comment]
No, this message is provided by android api when you need to add your app to device power optimization white list, so the message cannot be changed, maybe you can read android documentation for more information.
https://developer.android.com/reference/android/provider/Settings.html?authuser=3#ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS
