### ISSUE TITLE
Copy/Paste bug in IsIgnoringDataSaver() method

### ISSUE THREAD

**Issue by jimlerza** [snt1017/cordova-plugin-power-optimization#4]
The `IsIgnoringDataSaver()` method is passing the `IsIgnoringBatteryOptimizations` action to the native Android class where it should be passing the `IsIgnoringDataSaver` action instead.

Change this:

`exports.IsIgnoringDataSaver = function (arg0) {`
`    return execute_boolean('IsIgnoringBatteryOptimizations', arg0);`
`};`

To this:

`exports.IsIgnoringDataSaver = function (arg0) {`
`    return execute_boolean('IsIgnoringDataSaver', arg0);`
`};`

**Comment by snt1017** [comment]
Thanks!

**Comment by jimlerza** [comment]
Do you mind to send another message in this thread once you've released this to npm?

TIA
